
# Docker Compose syntax version. Requires Docker Engine 1.13.0+
#
# NOTE: This is used for local setup ONLY.
version: '3.1'

# Create docker volumes using the default driver
volumes:
  sc-backend-logs:

# Docker services
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
    - "3309:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root

  sc-backend:
    container_name: sc-backend
    image: sc-backend
    ports:
    - "3000:3000"
    links:
    - mysql:mysql.localhost
    depends_on:
    - mysql